### ISSUE TITLE
Recent weights from Nov 2020 preprint

### ISSUE THREAD

**Issue by andreabc** [PNNL-Comp-Mass-Spec/Kaiko#3]
Hi, I'm interested in trying out this model, I noticed you guys have updated your bioRxiv paper, and I found the weights from 1/8/19 in the MassIVE database, have you uploaded the new trained model somewhere else? thanks!

**Comment by coldfire79** [comment]
No, we haven't updated the pre-trained model since then. Since training module was based on the python 2 and out-of-date tensorflow, we are going to refactor the codebase to retrain and upgrade the model by adding more data. But you can still use this model with the docker.
